### ISSUE TITLE
登录界面及权限认证

### ISSUE THREAD

**Issue by Zhuyi731** [Zhuyi731/Tenda_CI_server#14]
**需求场景**
做登录及权限的认证，避免一些安全问题。并且了解当前操作CI的人员及操作情况。

**需求解决方案**
添加登录模块及权限认证

**Comment by Zhuyi731** [comment]
- 由杨春梅完成此模块

**Comment by sweet-sheep** [comment]
已完成登陆模块
**实现方案**
使用 session 验证登陆  通过路由时判断session拦截请求
